
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wugkdcizqdtjfqjznczx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1Z2tkY2l6cWR0amZxanpuY3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTQ4ODYsImV4cCI6MjA2NjU3MDg4Nn0.vVdaLZOMhwu7LumHmhfihoLg6N8gVLIp6n2bSdurnF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
